version: '3.8'
services:
  backend:
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8501:8501"
    environment:
      - RD_HOST=redis-hostname
      - RD_PORT=6379
    depends_on:
      - redis-server
  redis-server:
    image: redis:6.2-alpine
    hostname: redis-hostname
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 